name: Build ESP32 Firmware

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install Libraries
      run: |
        arduino-cli lib install "modbus-esp8266"
        arduino-cli lib install "Adafruit NeoPixel"
        arduino-cli lib install "PubSubClient"
        arduino-cli lib install "NimBLE-Arduino"

    - name: Compile Firmware
      run: |
        arduino-cli compile \
          --fqbn esp32:esp32:esp32s3 \
          --output-dir build \
          .

    - name: Copy BIN to root
      run: |
        BIN_FILE=$(find build -name "*.bin" | head -n 1)
        cp "$BIN_FILE" solar.bin


    - name: Commit and Push BIN
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
    
        git add solar.bin
    
        if git diff --cached --quiet; then
          echo "No changes"
          exit 0
        fi
    
        git commit -m "Auto update solar.bin"
    
        git fetch origin main
        git rebase origin/main
    
        git push origin HEAD:main


